### PR TITLE
Add documentation on SDK extensions

### PR DESCRIPTION
**Pull request by sebastian-de**

### CODE REVIEW

**Comment by sebastian-de** [comment]
@Erick555 I need your help here. Please have a look at the instructions regarding SDK extensions.
According to https://github.com/flathub/com.visualstudio.code-oss/issues/40#issuecomment-840604865 `FLATPAK_ENABLE_SDK_EXT=rust-stable` should be enough, but the SDK won't show up in my path - I still have to run `source /usr/lib/sdk/rust-stable/enable.sh`.
Do you know what I'm missing?

**Comment by Erick555** [comment]
`FLATPAK_ENABLE_SDK_EXT` is a feature of [this](https://github.com/flathub/ide-flatpak-wrapper/) third party tool not flatpak itself so you need to bundle it with your app if you want to use it, see instructions at https://github.com/flathub/ide-flatpak-wrapper/#usage

**Comment by sebastian-de** [comment]
Ah, thanks. So without ide-flatpak-wrapper the user has to run `source /usr/lib/sdk/rust-stable/enable.sh` or edit `$PATH` manually for every SDK?

**Comment by Erick555** [comment]
yes

**Pull request merged**
