### PR TITLE
test build

### PR DESCRIPTION
**Pull request by sebastian-de**

### CODE REVIEW

**Comment by VarLad** [comment]
@sebastian-de Can we keep this PR alive (forever) so that others can try the latest commits?

**Comment by sebastian-de** [comment]
Sure, why not. But please don't expect this to be updated daily. I will push updates from time to time, though.

**Comment by Not-a-web-Developer** [comment]
writing a comment simply to get this working again

**Comment by sebastian-de** [comment]
Please see https://github.com/flathub/dev.lapce.lapce/issues/16
If you want to test nightly builds, you can use the binaries provided upstream.

See also my comment above:
> Sure, why not. But please don't expect this to be updated daily. I will push updates from time to time, though.

**Comment by Newbytee** [comment]
Wouldn't it be better to set up a Flathub Beta branch that builds the master branch on a daily basis?

**Comment by ghishadow** [comment]
@Newbytee https://github.com/flathub/dev.lapce.lapce/issues/16#issuecomment-1173889580

**Comment by Newbytee** [comment]
How about re-packaging the nightly builds from upstream? This way you'd mitigate the problem of using build time significantly.

**Comment by sebastian-de** [comment]
Since the request for nightly builds comes up from time to time, I added a [README](https://github.com/flathub/dev.lapce.lapce/blob/master/README.md) with instructions on how to build a snapshot flatpak yourself.

**Comment by sebastian-de** [comment]
I'll include the commit from PR #28 in the test build from now on - please test with different shells/configurations and report back if anything breaks.

**Pull request closed without merging**
