### PR TITLE
Depend on rust extension

### PR DESCRIPTION
**Pull request by Erick555**
This makes rust extension being auto-downloaded alongside app and ready for use

Please test

### CODE REVIEW

**Comment by Erick555** [comment]
Hm, it doesn't seem to download the extension. I thought same technique worked some time ago.

**Comment by sebastian-de** [comment]
I'll have another look at this tomorrow, but I'm still not really sure what we gain from this.
With https://github.com/lapce/lapce/pull/1084 merged, we get a host shell by default and the Lapce Rust plugin works fine, without the rust-stable extension being mounted.

**Comment by Erick555** [comment]
Some people may expect this app will be self-contained - without rust available on host. This came up on matrix channel where they asked for help so I thought we can make this work out of the box.

**Comment by Erick555** [comment]
Perhaps you can add instructions how to install and activate rust extension in README.

**Comment by sebastian-de** [comment]
> Some people may expect this app will be self-contained - without rust available on host. This came up on matrix channel where they asked for help so I thought we can make this work out of the box.

Thank you for your input.

I'm open to this discussion, but I'm sceptical if it's a realistic goal to make this flatpak self-contained. Adding support for every language Lapce can handle will also add a lot of complexity. This is possible of course (have a look at [Gnome Builder](https://github.com/flathub/org.gnome.Builder/blob/master/org.gnome.Builder.json) for example), but since this is the first flatpak I maintain, I'd like to keep things as simple as possible for the time being.

To be honest, I'm not even 100% sure if flatpak is the right choice for a code editor/IDE, see https://github.com/flathub/dev.lapce.lapce/issues/1#issuecomment-1242392723 for example.

But I'll keep maintaining it and do as best as I can to make it usable!



> Perhaps you can add instructions how to install and activate rust extension in README.

Sure, I can do that.

**Pull request closed without merging**
